// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: S2C_Protocol_Danmaku.proto
// Protobuf C++ Version: 6.33.4

#ifndef S2C_5fProtocol_5fDanmaku_2eproto_2epb_2eh
#define S2C_5fProtocol_5fDanmaku_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "S2C_Protocol_Common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_S2C_5fProtocol_5fDanmaku_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_S2C_5fProtocol_5fDanmaku_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_S2C_5fProtocol_5fDanmaku_2eproto;
}  // extern "C"
namespace S2C_Protocol {
class S_DanmakuResult;
struct S_DanmakuResultDefaultTypeInternal;
extern S_DanmakuResultDefaultTypeInternal _S_DanmakuResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_DanmakuResult_class_data_;
class S_DanmakuState;
struct S_DanmakuStateDefaultTypeInternal;
extern S_DanmakuStateDefaultTypeInternal _S_DanmakuState_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_DanmakuState_class_data_;
}  // namespace S2C_Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace S2C_Protocol {

// ===================================================================


// -------------------------------------------------------------------

class S_DanmakuResult final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:S2C_Protocol.S_DanmakuResult) */ {
 public:
  inline S_DanmakuResult() : S_DanmakuResult(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_DanmakuResult* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_DanmakuResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_DanmakuResult(::google::protobuf::internal::ConstantInitialized);

  inline S_DanmakuResult(const S_DanmakuResult& from) : S_DanmakuResult(nullptr, from) {}
  inline S_DanmakuResult(S_DanmakuResult&& from) noexcept
      : S_DanmakuResult(nullptr, ::std::move(from)) {}
  inline S_DanmakuResult& operator=(const S_DanmakuResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_DanmakuResult& operator=(S_DanmakuResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_DanmakuResult& default_instance() {
    return *reinterpret_cast<const S_DanmakuResult*>(
        &_S_DanmakuResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(S_DanmakuResult& a, S_DanmakuResult& b) { a.Swap(&b); }
  inline void Swap(S_DanmakuResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_DanmakuResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_DanmakuResult* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<S_DanmakuResult>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const S_DanmakuResult& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const S_DanmakuResult& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "S2C_Protocol.S_DanmakuResult"; }

  explicit S_DanmakuResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_DanmakuResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_DanmakuResult& from);
  S_DanmakuResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_DanmakuResult&& from) noexcept
      : S_DanmakuResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:S2C_Protocol.S_DanmakuResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_S2C_5fProtocol_5fDanmaku_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_DanmakuResult_class_data_;
// -------------------------------------------------------------------

class S_DanmakuState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:S2C_Protocol.S_DanmakuState) */ {
 public:
  inline S_DanmakuState() : S_DanmakuState(nullptr) {}
  ~S_DanmakuState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_DanmakuState* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_DanmakuState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_DanmakuState(::google::protobuf::internal::ConstantInitialized);

  inline S_DanmakuState(const S_DanmakuState& from) : S_DanmakuState(nullptr, from) {}
  inline S_DanmakuState(S_DanmakuState&& from) noexcept
      : S_DanmakuState(nullptr, ::std::move(from)) {}
  inline S_DanmakuState& operator=(const S_DanmakuState& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_DanmakuState& operator=(S_DanmakuState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_DanmakuState& default_instance() {
    return *reinterpret_cast<const S_DanmakuState*>(
        &_S_DanmakuState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(S_DanmakuState& a, S_DanmakuState& b) { a.Swap(&b); }
  inline void Swap(S_DanmakuState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_DanmakuState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_DanmakuState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_DanmakuState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_DanmakuState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_DanmakuState& from) { S_DanmakuState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_DanmakuState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "S2C_Protocol.S_DanmakuState"; }

  explicit S_DanmakuState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_DanmakuState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_DanmakuState& from);
  S_DanmakuState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_DanmakuState&& from) noexcept
      : S_DanmakuState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectsFieldNumber = 1,
  };
  // repeated .S2C_Protocol.UnityGameObject objects = 1;
  int objects_size() const;
  private:
  int _internal_objects_size() const;

  public:
  void clear_objects() ;
  ::S2C_Protocol::UnityGameObject* PROTOBUF_NONNULL mutable_objects(int index);
  ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>* PROTOBUF_NONNULL mutable_objects();

  private:
  const ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>& _internal_objects() const;
  ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>* PROTOBUF_NONNULL _internal_mutable_objects();
  public:
  const ::S2C_Protocol::UnityGameObject& objects(int index) const;
  ::S2C_Protocol::UnityGameObject* PROTOBUF_NONNULL add_objects();
  const ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>& objects() const;
  // @@protoc_insertion_point(class_scope:S2C_Protocol.S_DanmakuState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_DanmakuState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::S2C_Protocol::UnityGameObject > objects_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_S2C_5fProtocol_5fDanmaku_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_DanmakuState_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// S_DanmakuState

// repeated .S2C_Protocol.UnityGameObject objects = 1;
inline int S_DanmakuState::_internal_objects_size() const {
  return _internal_objects().size();
}
inline int S_DanmakuState::objects_size() const {
  return _internal_objects_size();
}
inline ::S2C_Protocol::UnityGameObject* PROTOBUF_NONNULL S_DanmakuState::mutable_objects(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:S2C_Protocol.S_DanmakuState.objects)
  return _internal_mutable_objects()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>* PROTOBUF_NONNULL S_DanmakuState::mutable_objects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:S2C_Protocol.S_DanmakuState.objects)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_objects();
}
inline const ::S2C_Protocol::UnityGameObject& S_DanmakuState::objects(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:S2C_Protocol.S_DanmakuState.objects)
  return _internal_objects().Get(index);
}
inline ::S2C_Protocol::UnityGameObject* PROTOBUF_NONNULL S_DanmakuState::add_objects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::S2C_Protocol::UnityGameObject* _add =
      _internal_mutable_objects()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:S2C_Protocol.S_DanmakuState.objects)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>& S_DanmakuState::objects() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:S2C_Protocol.S_DanmakuState.objects)
  return _internal_objects();
}
inline const ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>&
S_DanmakuState::_internal_objects() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.objects_;
}
inline ::google::protobuf::RepeatedPtrField<::S2C_Protocol::UnityGameObject>* PROTOBUF_NONNULL
S_DanmakuState::_internal_mutable_objects() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.objects_;
}

// -------------------------------------------------------------------

// S_DanmakuResult

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace S2C_Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // S2C_5fProtocol_5fDanmaku_2eproto_2epb_2eh
