// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: S2C_Protocol_Mole.proto
// Protobuf C++ Version: 5.29.5

#include "S2C_Protocol_Mole.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace S2C_Protocol {

inline constexpr S_M_State::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ids_{},
        playerid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_M_State::S_M_State(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_M_StateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_M_StateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_M_StateDefaultTypeInternal() {}
  union {
    S_M_State _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_M_StateDefaultTypeInternal _S_M_State_default_instance_;

inline constexpr S_M_SetSlotState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : slotidx_{0},
        state_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_M_SetSlotState::S_M_SetSlotState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_M_SetSlotStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_M_SetSlotStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_M_SetSlotStateDefaultTypeInternal() {}
  union {
    S_M_SetSlotState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_M_SetSlotStateDefaultTypeInternal _S_M_SetSlotState_default_instance_;

inline constexpr S_M_Result::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : scores_{},
        _scores_cached_byte_size_{0},
        iswinner_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_M_Result::S_M_Result(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_M_ResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_M_ResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_M_ResultDefaultTypeInternal() {}
  union {
    S_M_Result _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_M_ResultDefaultTypeInternal _S_M_Result_default_instance_;

inline constexpr S_M_ResponseHitSlot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : isstunned_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_M_ResponseHitSlot::S_M_ResponseHitSlot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_M_ResponseHitSlotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_M_ResponseHitSlotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_M_ResponseHitSlotDefaultTypeInternal() {}
  union {
    S_M_ResponseHitSlot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_M_ResponseHitSlotDefaultTypeInternal _S_M_ResponseHitSlot_default_instance_;

inline constexpr S_M_RenewScores::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : scores_{},
        _scores_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_M_RenewScores::S_M_RenewScores(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_M_RenewScoresDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_M_RenewScoresDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_M_RenewScoresDefaultTypeInternal() {}
  union {
    S_M_RenewScores _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_M_RenewScoresDefaultTypeInternal _S_M_RenewScores_default_instance_;

inline constexpr S_M_ReadyForStart::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : countdown_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_M_ReadyForStart::S_M_ReadyForStart(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_M_ReadyForStartDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_M_ReadyForStartDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_M_ReadyForStartDefaultTypeInternal() {}
  union {
    S_M_ReadyForStart _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_M_ReadyForStartDefaultTypeInternal _S_M_ReadyForStart_default_instance_;

inline constexpr C_M_HitSlot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : slotidx_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR C_M_HitSlot::C_M_HitSlot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C_M_HitSlotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_M_HitSlotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_M_HitSlotDefaultTypeInternal() {}
  union {
    C_M_HitSlot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_M_HitSlotDefaultTypeInternal _C_M_HitSlot_default_instance_;
}  // namespace S2C_Protocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_S2C_5fProtocol_5fMole_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_S2C_5fProtocol_5fMole_2eproto = nullptr;
const ::uint32_t
    TableStruct_S2C_5fProtocol_5fMole_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_State, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_State, _impl_.playerid_),
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_State, _impl_.ids_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_Result, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_Result, _impl_.iswinner_),
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_Result, _impl_.scores_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_SetSlotState, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_SetSlotState, _impl_.slotidx_),
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_SetSlotState, _impl_.state_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::C_M_HitSlot, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::C_M_HitSlot, _impl_.slotidx_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_ResponseHitSlot, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_ResponseHitSlot, _impl_.isstunned_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_RenewScores, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_RenewScores, _impl_.scores_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_ReadyForStart, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::S2C_Protocol::S_M_ReadyForStart, _impl_.countdown_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::S2C_Protocol::S_M_State)},
        {10, -1, -1, sizeof(::S2C_Protocol::S_M_Result)},
        {20, -1, -1, sizeof(::S2C_Protocol::S_M_SetSlotState)},
        {30, -1, -1, sizeof(::S2C_Protocol::C_M_HitSlot)},
        {39, -1, -1, sizeof(::S2C_Protocol::S_M_ResponseHitSlot)},
        {48, -1, -1, sizeof(::S2C_Protocol::S_M_RenewScores)},
        {57, -1, -1, sizeof(::S2C_Protocol::S_M_ReadyForStart)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::S2C_Protocol::_S_M_State_default_instance_._instance,
    &::S2C_Protocol::_S_M_Result_default_instance_._instance,
    &::S2C_Protocol::_S_M_SetSlotState_default_instance_._instance,
    &::S2C_Protocol::_C_M_HitSlot_default_instance_._instance,
    &::S2C_Protocol::_S_M_ResponseHitSlot_default_instance_._instance,
    &::S2C_Protocol::_S_M_RenewScores_default_instance_._instance,
    &::S2C_Protocol::_S_M_ReadyForStart_default_instance_._instance,
};
const char descriptor_table_protodef_S2C_5fProtocol_5fMole_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027S2C_Protocol_Mole.proto\022\014S2C_Protocol\032"
    "\031S2C_Protocol_Common.proto\"*\n\tS_M_State\022"
    "\020\n\010playerId\030\001 \001(\005\022\013\n\003ids\030\002 \003(\t\".\n\nS_M_Re"
    "sult\022\020\n\010isWinner\030\001 \001(\010\022\016\n\006scores\030\002 \003(\005\"2"
    "\n\020S_M_SetSlotState\022\017\n\007slotIdx\030\001 \001(\005\022\r\n\005s"
    "tate\030\002 \001(\005\"\036\n\013C_M_HitSlot\022\017\n\007slotIdx\030\001 \001"
    "(\005\"(\n\023S_M_ResponseHitSlot\022\021\n\tisStunned\030\001"
    " \001(\010\"!\n\017S_M_RenewScores\022\016\n\006scores\030\001 \003(\005\""
    "&\n\021S_M_ReadyForStart\022\021\n\tcountdown\030\001 \001(\005B"
    "\033\252\002\030Google.Protobuf.Protocolb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_S2C_5fProtocol_5fMole_2eproto_deps[1] =
    {
        &::descriptor_table_S2C_5fProtocol_5fCommon_2eproto,
};
static ::absl::once_flag descriptor_table_S2C_5fProtocol_5fMole_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_S2C_5fProtocol_5fMole_2eproto = {
    false,
    false,
    396,
    descriptor_table_protodef_S2C_5fProtocol_5fMole_2eproto,
    "S2C_Protocol_Mole.proto",
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto_once,
    descriptor_table_S2C_5fProtocol_5fMole_2eproto_deps,
    1,
    7,
    schemas,
    file_default_instances,
    TableStruct_S2C_5fProtocol_5fMole_2eproto::offsets,
    file_level_enum_descriptors_S2C_5fProtocol_5fMole_2eproto,
    file_level_service_descriptors_S2C_5fProtocol_5fMole_2eproto,
};
namespace S2C_Protocol {
// ===================================================================

class S_M_State::_Internal {
 public:
};

S_M_State::S_M_State(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_Protocol.S_M_State)
}
inline PROTOBUF_NDEBUG_INLINE S_M_State::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::S2C_Protocol::S_M_State& from_msg)
      : ids_{visibility, arena, from.ids_},
        _cached_size_{0} {}

S_M_State::S_M_State(
    ::google::protobuf::Arena* arena,
    const S_M_State& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S_M_State* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.playerid_ = from._impl_.playerid_;

  // @@protoc_insertion_point(copy_constructor:S2C_Protocol.S_M_State)
}
inline PROTOBUF_NDEBUG_INLINE S_M_State::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ids_{visibility, arena},
        _cached_size_{0} {}

inline void S_M_State::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.playerid_ = {};
}
S_M_State::~S_M_State() {
  // @@protoc_insertion_point(destructor:S2C_Protocol.S_M_State)
  SharedDtor(*this);
}
inline void S_M_State::SharedDtor(MessageLite& self) {
  S_M_State& this_ = static_cast<S_M_State&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* S_M_State::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_M_State(arena);
}
constexpr auto S_M_State::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(S_M_State, _impl_.ids_) +
          decltype(S_M_State::_impl_.ids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(S_M_State), alignof(S_M_State), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&S_M_State::PlacementNew_,
                                 sizeof(S_M_State),
                                 alignof(S_M_State));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_M_State::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_M_State_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_M_State::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_M_State>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_M_State::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_M_State>(), &S_M_State::ByteSizeLong,
            &S_M_State::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_M_State, _impl_._cached_size_),
        false,
    },
    &S_M_State::kDescriptorMethods,
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_M_State::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> S_M_State::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_Protocol::S_M_State>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string ids = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_State, _impl_.ids_)}},
    // int32 playerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S_M_State, _impl_.playerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_State, _impl_.playerid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 playerId = 1;
    {PROTOBUF_FIELD_OFFSET(S_M_State, _impl_.playerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated string ids = 2;
    {PROTOBUF_FIELD_OFFSET(S_M_State, _impl_.ids_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\26\0\3\0\0\0\0\0"
    "S2C_Protocol.S_M_State"
    "ids"
  }},
};

PROTOBUF_NOINLINE void S_M_State::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_Protocol.S_M_State)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ids_.Clear();
  _impl_.playerid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_M_State::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_M_State& this_ = static_cast<const S_M_State&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_M_State::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_M_State& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:S2C_Protocol.S_M_State)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 playerId = 1;
          if (this_._internal_playerid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_playerid(), target);
          }

          // repeated string ids = 2;
          for (int i = 0, n = this_._internal_ids_size(); i < n; ++i) {
            const auto& s = this_._internal_ids().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "S2C_Protocol.S_M_State.ids");
            target = stream->WriteString(2, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:S2C_Protocol.S_M_State)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_M_State::ByteSizeLong(const MessageLite& base) {
          const S_M_State& this_ = static_cast<const S_M_State&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_M_State::ByteSizeLong() const {
          const S_M_State& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:S2C_Protocol.S_M_State)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string ids = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_ids().size());
              for (int i = 0, n = this_._internal_ids().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_ids().Get(i));
              }
            }
          }
           {
            // int32 playerId = 1;
            if (this_._internal_playerid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_playerid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_M_State::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_M_State*>(&to_msg);
  auto& from = static_cast<const S_M_State&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_Protocol.S_M_State)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ids()->MergeFrom(from._internal_ids());
  if (from._internal_playerid() != 0) {
    _this->_impl_.playerid_ = from._impl_.playerid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_M_State::CopyFrom(const S_M_State& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_Protocol.S_M_State)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_M_State::InternalSwap(S_M_State* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ids_.InternalSwap(&other->_impl_.ids_);
        swap(_impl_.playerid_, other->_impl_.playerid_);
}

::google::protobuf::Metadata S_M_State::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S_M_Result::_Internal {
 public:
};

S_M_Result::S_M_Result(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_Protocol.S_M_Result)
}
inline PROTOBUF_NDEBUG_INLINE S_M_Result::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::S2C_Protocol::S_M_Result& from_msg)
      : scores_{visibility, arena, from.scores_},
        _scores_cached_byte_size_{0},
        _cached_size_{0} {}

S_M_Result::S_M_Result(
    ::google::protobuf::Arena* arena,
    const S_M_Result& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S_M_Result* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.iswinner_ = from._impl_.iswinner_;

  // @@protoc_insertion_point(copy_constructor:S2C_Protocol.S_M_Result)
}
inline PROTOBUF_NDEBUG_INLINE S_M_Result::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : scores_{visibility, arena},
        _scores_cached_byte_size_{0},
        _cached_size_{0} {}

inline void S_M_Result::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.iswinner_ = {};
}
S_M_Result::~S_M_Result() {
  // @@protoc_insertion_point(destructor:S2C_Protocol.S_M_Result)
  SharedDtor(*this);
}
inline void S_M_Result::SharedDtor(MessageLite& self) {
  S_M_Result& this_ = static_cast<S_M_Result&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* S_M_Result::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_M_Result(arena);
}
constexpr auto S_M_Result::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(S_M_Result, _impl_.scores_) +
          decltype(S_M_Result::_impl_.scores_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(S_M_Result), alignof(S_M_Result), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&S_M_Result::PlacementNew_,
                                 sizeof(S_M_Result),
                                 alignof(S_M_Result));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_M_Result::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_M_Result_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_M_Result::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_M_Result>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_M_Result::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_M_Result>(), &S_M_Result::ByteSizeLong,
            &S_M_Result::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_M_Result, _impl_._cached_size_),
        false,
    },
    &S_M_Result::kDescriptorMethods,
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_M_Result::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> S_M_Result::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_Protocol::S_M_Result>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int32 scores = 2;
    {::_pbi::TcParser::FastV32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_Result, _impl_.scores_)}},
    // bool isWinner = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(S_M_Result, _impl_.iswinner_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_Result, _impl_.iswinner_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool isWinner = 1;
    {PROTOBUF_FIELD_OFFSET(S_M_Result, _impl_.iswinner_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // repeated int32 scores = 2;
    {PROTOBUF_FIELD_OFFSET(S_M_Result, _impl_.scores_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void S_M_Result::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_Protocol.S_M_Result)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scores_.Clear();
  _impl_.iswinner_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_M_Result::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_M_Result& this_ = static_cast<const S_M_Result&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_M_Result::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_M_Result& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:S2C_Protocol.S_M_Result)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool isWinner = 1;
          if (this_._internal_iswinner() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_iswinner(), target);
          }

          // repeated int32 scores = 2;
          {
            int byte_size = this_._impl_._scores_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  2, this_._internal_scores(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:S2C_Protocol.S_M_Result)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_M_Result::ByteSizeLong(const MessageLite& base) {
          const S_M_Result& this_ = static_cast<const S_M_Result&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_M_Result::ByteSizeLong() const {
          const S_M_Result& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:S2C_Protocol.S_M_Result)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 scores = 2;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_scores(), 1,
                      this_._impl_._scores_cached_byte_size_);
            }
          }
           {
            // bool isWinner = 1;
            if (this_._internal_iswinner() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_M_Result::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_M_Result*>(&to_msg);
  auto& from = static_cast<const S_M_Result&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_Protocol.S_M_Result)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_scores()->MergeFrom(from._internal_scores());
  if (from._internal_iswinner() != 0) {
    _this->_impl_.iswinner_ = from._impl_.iswinner_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_M_Result::CopyFrom(const S_M_Result& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_Protocol.S_M_Result)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_M_Result::InternalSwap(S_M_Result* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.scores_.InternalSwap(&other->_impl_.scores_);
        swap(_impl_.iswinner_, other->_impl_.iswinner_);
}

::google::protobuf::Metadata S_M_Result::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S_M_SetSlotState::_Internal {
 public:
};

S_M_SetSlotState::S_M_SetSlotState(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_Protocol.S_M_SetSlotState)
}
S_M_SetSlotState::S_M_SetSlotState(
    ::google::protobuf::Arena* arena, const S_M_SetSlotState& from)
    : S_M_SetSlotState(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE S_M_SetSlotState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void S_M_SetSlotState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, slotidx_),
           0,
           offsetof(Impl_, state_) -
               offsetof(Impl_, slotidx_) +
               sizeof(Impl_::state_));
}
S_M_SetSlotState::~S_M_SetSlotState() {
  // @@protoc_insertion_point(destructor:S2C_Protocol.S_M_SetSlotState)
  SharedDtor(*this);
}
inline void S_M_SetSlotState::SharedDtor(MessageLite& self) {
  S_M_SetSlotState& this_ = static_cast<S_M_SetSlotState&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* S_M_SetSlotState::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_M_SetSlotState(arena);
}
constexpr auto S_M_SetSlotState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S_M_SetSlotState),
                                            alignof(S_M_SetSlotState));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_M_SetSlotState::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_M_SetSlotState_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_M_SetSlotState::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_M_SetSlotState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_M_SetSlotState::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_M_SetSlotState>(), &S_M_SetSlotState::ByteSizeLong,
            &S_M_SetSlotState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_M_SetSlotState, _impl_._cached_size_),
        false,
    },
    &S_M_SetSlotState::kDescriptorMethods,
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_M_SetSlotState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> S_M_SetSlotState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_Protocol::S_M_SetSlotState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S_M_SetSlotState, _impl_.state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_SetSlotState, _impl_.state_)}},
    // int32 slotIdx = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S_M_SetSlotState, _impl_.slotidx_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_SetSlotState, _impl_.slotidx_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 slotIdx = 1;
    {PROTOBUF_FIELD_OFFSET(S_M_SetSlotState, _impl_.slotidx_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 state = 2;
    {PROTOBUF_FIELD_OFFSET(S_M_SetSlotState, _impl_.state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void S_M_SetSlotState::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_Protocol.S_M_SetSlotState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.slotidx_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.state_) -
      reinterpret_cast<char*>(&_impl_.slotidx_)) + sizeof(_impl_.state_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_M_SetSlotState::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_M_SetSlotState& this_ = static_cast<const S_M_SetSlotState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_M_SetSlotState::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_M_SetSlotState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:S2C_Protocol.S_M_SetSlotState)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 slotIdx = 1;
          if (this_._internal_slotidx() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_slotidx(), target);
          }

          // int32 state = 2;
          if (this_._internal_state() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_state(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:S2C_Protocol.S_M_SetSlotState)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_M_SetSlotState::ByteSizeLong(const MessageLite& base) {
          const S_M_SetSlotState& this_ = static_cast<const S_M_SetSlotState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_M_SetSlotState::ByteSizeLong() const {
          const S_M_SetSlotState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:S2C_Protocol.S_M_SetSlotState)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 slotIdx = 1;
            if (this_._internal_slotidx() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_slotidx());
            }
            // int32 state = 2;
            if (this_._internal_state() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_state());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_M_SetSlotState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_M_SetSlotState*>(&to_msg);
  auto& from = static_cast<const S_M_SetSlotState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_Protocol.S_M_SetSlotState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_slotidx() != 0) {
    _this->_impl_.slotidx_ = from._impl_.slotidx_;
  }
  if (from._internal_state() != 0) {
    _this->_impl_.state_ = from._impl_.state_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_M_SetSlotState::CopyFrom(const S_M_SetSlotState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_Protocol.S_M_SetSlotState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_M_SetSlotState::InternalSwap(S_M_SetSlotState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S_M_SetSlotState, _impl_.state_)
      + sizeof(S_M_SetSlotState::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(S_M_SetSlotState, _impl_.slotidx_)>(
          reinterpret_cast<char*>(&_impl_.slotidx_),
          reinterpret_cast<char*>(&other->_impl_.slotidx_));
}

::google::protobuf::Metadata S_M_SetSlotState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class C_M_HitSlot::_Internal {
 public:
};

C_M_HitSlot::C_M_HitSlot(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_Protocol.C_M_HitSlot)
}
C_M_HitSlot::C_M_HitSlot(
    ::google::protobuf::Arena* arena, const C_M_HitSlot& from)
    : C_M_HitSlot(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE C_M_HitSlot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void C_M_HitSlot::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.slotidx_ = {};
}
C_M_HitSlot::~C_M_HitSlot() {
  // @@protoc_insertion_point(destructor:S2C_Protocol.C_M_HitSlot)
  SharedDtor(*this);
}
inline void C_M_HitSlot::SharedDtor(MessageLite& self) {
  C_M_HitSlot& this_ = static_cast<C_M_HitSlot&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* C_M_HitSlot::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) C_M_HitSlot(arena);
}
constexpr auto C_M_HitSlot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(C_M_HitSlot),
                                            alignof(C_M_HitSlot));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull C_M_HitSlot::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_C_M_HitSlot_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &C_M_HitSlot::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<C_M_HitSlot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &C_M_HitSlot::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<C_M_HitSlot>(), &C_M_HitSlot::ByteSizeLong,
            &C_M_HitSlot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(C_M_HitSlot, _impl_._cached_size_),
        false,
    },
    &C_M_HitSlot::kDescriptorMethods,
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* C_M_HitSlot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> C_M_HitSlot::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_Protocol::C_M_HitSlot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 slotIdx = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(C_M_HitSlot, _impl_.slotidx_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(C_M_HitSlot, _impl_.slotidx_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 slotIdx = 1;
    {PROTOBUF_FIELD_OFFSET(C_M_HitSlot, _impl_.slotidx_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void C_M_HitSlot::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_Protocol.C_M_HitSlot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.slotidx_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* C_M_HitSlot::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const C_M_HitSlot& this_ = static_cast<const C_M_HitSlot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* C_M_HitSlot::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const C_M_HitSlot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:S2C_Protocol.C_M_HitSlot)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 slotIdx = 1;
          if (this_._internal_slotidx() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_slotidx(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:S2C_Protocol.C_M_HitSlot)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t C_M_HitSlot::ByteSizeLong(const MessageLite& base) {
          const C_M_HitSlot& this_ = static_cast<const C_M_HitSlot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t C_M_HitSlot::ByteSizeLong() const {
          const C_M_HitSlot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:S2C_Protocol.C_M_HitSlot)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 slotIdx = 1;
            if (this_._internal_slotidx() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_slotidx());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void C_M_HitSlot::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<C_M_HitSlot*>(&to_msg);
  auto& from = static_cast<const C_M_HitSlot&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_Protocol.C_M_HitSlot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_slotidx() != 0) {
    _this->_impl_.slotidx_ = from._impl_.slotidx_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void C_M_HitSlot::CopyFrom(const C_M_HitSlot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_Protocol.C_M_HitSlot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C_M_HitSlot::InternalSwap(C_M_HitSlot* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.slotidx_, other->_impl_.slotidx_);
}

::google::protobuf::Metadata C_M_HitSlot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S_M_ResponseHitSlot::_Internal {
 public:
};

S_M_ResponseHitSlot::S_M_ResponseHitSlot(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_Protocol.S_M_ResponseHitSlot)
}
S_M_ResponseHitSlot::S_M_ResponseHitSlot(
    ::google::protobuf::Arena* arena, const S_M_ResponseHitSlot& from)
    : S_M_ResponseHitSlot(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE S_M_ResponseHitSlot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void S_M_ResponseHitSlot::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.isstunned_ = {};
}
S_M_ResponseHitSlot::~S_M_ResponseHitSlot() {
  // @@protoc_insertion_point(destructor:S2C_Protocol.S_M_ResponseHitSlot)
  SharedDtor(*this);
}
inline void S_M_ResponseHitSlot::SharedDtor(MessageLite& self) {
  S_M_ResponseHitSlot& this_ = static_cast<S_M_ResponseHitSlot&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* S_M_ResponseHitSlot::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_M_ResponseHitSlot(arena);
}
constexpr auto S_M_ResponseHitSlot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S_M_ResponseHitSlot),
                                            alignof(S_M_ResponseHitSlot));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_M_ResponseHitSlot::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_M_ResponseHitSlot_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_M_ResponseHitSlot::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_M_ResponseHitSlot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_M_ResponseHitSlot::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_M_ResponseHitSlot>(), &S_M_ResponseHitSlot::ByteSizeLong,
            &S_M_ResponseHitSlot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_M_ResponseHitSlot, _impl_._cached_size_),
        false,
    },
    &S_M_ResponseHitSlot::kDescriptorMethods,
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_M_ResponseHitSlot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> S_M_ResponseHitSlot::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_Protocol::S_M_ResponseHitSlot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool isStunned = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(S_M_ResponseHitSlot, _impl_.isstunned_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_ResponseHitSlot, _impl_.isstunned_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool isStunned = 1;
    {PROTOBUF_FIELD_OFFSET(S_M_ResponseHitSlot, _impl_.isstunned_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void S_M_ResponseHitSlot::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_Protocol.S_M_ResponseHitSlot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.isstunned_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_M_ResponseHitSlot::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_M_ResponseHitSlot& this_ = static_cast<const S_M_ResponseHitSlot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_M_ResponseHitSlot::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_M_ResponseHitSlot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:S2C_Protocol.S_M_ResponseHitSlot)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool isStunned = 1;
          if (this_._internal_isstunned() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_isstunned(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:S2C_Protocol.S_M_ResponseHitSlot)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_M_ResponseHitSlot::ByteSizeLong(const MessageLite& base) {
          const S_M_ResponseHitSlot& this_ = static_cast<const S_M_ResponseHitSlot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_M_ResponseHitSlot::ByteSizeLong() const {
          const S_M_ResponseHitSlot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:S2C_Protocol.S_M_ResponseHitSlot)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool isStunned = 1;
            if (this_._internal_isstunned() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_M_ResponseHitSlot::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_M_ResponseHitSlot*>(&to_msg);
  auto& from = static_cast<const S_M_ResponseHitSlot&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_Protocol.S_M_ResponseHitSlot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_isstunned() != 0) {
    _this->_impl_.isstunned_ = from._impl_.isstunned_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_M_ResponseHitSlot::CopyFrom(const S_M_ResponseHitSlot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_Protocol.S_M_ResponseHitSlot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_M_ResponseHitSlot::InternalSwap(S_M_ResponseHitSlot* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.isstunned_, other->_impl_.isstunned_);
}

::google::protobuf::Metadata S_M_ResponseHitSlot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S_M_RenewScores::_Internal {
 public:
};

S_M_RenewScores::S_M_RenewScores(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_Protocol.S_M_RenewScores)
}
inline PROTOBUF_NDEBUG_INLINE S_M_RenewScores::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::S2C_Protocol::S_M_RenewScores& from_msg)
      : scores_{visibility, arena, from.scores_},
        _scores_cached_byte_size_{0},
        _cached_size_{0} {}

S_M_RenewScores::S_M_RenewScores(
    ::google::protobuf::Arena* arena,
    const S_M_RenewScores& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S_M_RenewScores* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:S2C_Protocol.S_M_RenewScores)
}
inline PROTOBUF_NDEBUG_INLINE S_M_RenewScores::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : scores_{visibility, arena},
        _scores_cached_byte_size_{0},
        _cached_size_{0} {}

inline void S_M_RenewScores::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
S_M_RenewScores::~S_M_RenewScores() {
  // @@protoc_insertion_point(destructor:S2C_Protocol.S_M_RenewScores)
  SharedDtor(*this);
}
inline void S_M_RenewScores::SharedDtor(MessageLite& self) {
  S_M_RenewScores& this_ = static_cast<S_M_RenewScores&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* S_M_RenewScores::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_M_RenewScores(arena);
}
constexpr auto S_M_RenewScores::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(S_M_RenewScores, _impl_.scores_) +
          decltype(S_M_RenewScores::_impl_.scores_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(S_M_RenewScores), alignof(S_M_RenewScores), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&S_M_RenewScores::PlacementNew_,
                                 sizeof(S_M_RenewScores),
                                 alignof(S_M_RenewScores));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_M_RenewScores::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_M_RenewScores_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_M_RenewScores::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_M_RenewScores>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_M_RenewScores::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_M_RenewScores>(), &S_M_RenewScores::ByteSizeLong,
            &S_M_RenewScores::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_M_RenewScores, _impl_._cached_size_),
        false,
    },
    &S_M_RenewScores::kDescriptorMethods,
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_M_RenewScores::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> S_M_RenewScores::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_Protocol::S_M_RenewScores>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int32 scores = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_RenewScores, _impl_.scores_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 scores = 1;
    {PROTOBUF_FIELD_OFFSET(S_M_RenewScores, _impl_.scores_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void S_M_RenewScores::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_Protocol.S_M_RenewScores)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scores_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_M_RenewScores::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_M_RenewScores& this_ = static_cast<const S_M_RenewScores&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_M_RenewScores::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_M_RenewScores& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:S2C_Protocol.S_M_RenewScores)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated int32 scores = 1;
          {
            int byte_size = this_._impl_._scores_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  1, this_._internal_scores(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:S2C_Protocol.S_M_RenewScores)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_M_RenewScores::ByteSizeLong(const MessageLite& base) {
          const S_M_RenewScores& this_ = static_cast<const S_M_RenewScores&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_M_RenewScores::ByteSizeLong() const {
          const S_M_RenewScores& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:S2C_Protocol.S_M_RenewScores)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 scores = 1;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_scores(), 1,
                      this_._impl_._scores_cached_byte_size_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_M_RenewScores::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_M_RenewScores*>(&to_msg);
  auto& from = static_cast<const S_M_RenewScores&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_Protocol.S_M_RenewScores)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_scores()->MergeFrom(from._internal_scores());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_M_RenewScores::CopyFrom(const S_M_RenewScores& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_Protocol.S_M_RenewScores)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_M_RenewScores::InternalSwap(S_M_RenewScores* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.scores_.InternalSwap(&other->_impl_.scores_);
}

::google::protobuf::Metadata S_M_RenewScores::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S_M_ReadyForStart::_Internal {
 public:
};

S_M_ReadyForStart::S_M_ReadyForStart(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_Protocol.S_M_ReadyForStart)
}
S_M_ReadyForStart::S_M_ReadyForStart(
    ::google::protobuf::Arena* arena, const S_M_ReadyForStart& from)
    : S_M_ReadyForStart(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE S_M_ReadyForStart::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void S_M_ReadyForStart::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.countdown_ = {};
}
S_M_ReadyForStart::~S_M_ReadyForStart() {
  // @@protoc_insertion_point(destructor:S2C_Protocol.S_M_ReadyForStart)
  SharedDtor(*this);
}
inline void S_M_ReadyForStart::SharedDtor(MessageLite& self) {
  S_M_ReadyForStart& this_ = static_cast<S_M_ReadyForStart&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* S_M_ReadyForStart::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_M_ReadyForStart(arena);
}
constexpr auto S_M_ReadyForStart::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S_M_ReadyForStart),
                                            alignof(S_M_ReadyForStart));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_M_ReadyForStart::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_M_ReadyForStart_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_M_ReadyForStart::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_M_ReadyForStart>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_M_ReadyForStart::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_M_ReadyForStart>(), &S_M_ReadyForStart::ByteSizeLong,
            &S_M_ReadyForStart::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_M_ReadyForStart, _impl_._cached_size_),
        false,
    },
    &S_M_ReadyForStart::kDescriptorMethods,
    &descriptor_table_S2C_5fProtocol_5fMole_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_M_ReadyForStart::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> S_M_ReadyForStart::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_Protocol::S_M_ReadyForStart>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 countdown = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S_M_ReadyForStart, _impl_.countdown_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S_M_ReadyForStart, _impl_.countdown_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 countdown = 1;
    {PROTOBUF_FIELD_OFFSET(S_M_ReadyForStart, _impl_.countdown_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void S_M_ReadyForStart::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_Protocol.S_M_ReadyForStart)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.countdown_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_M_ReadyForStart::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_M_ReadyForStart& this_ = static_cast<const S_M_ReadyForStart&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_M_ReadyForStart::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_M_ReadyForStart& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:S2C_Protocol.S_M_ReadyForStart)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 countdown = 1;
          if (this_._internal_countdown() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_countdown(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:S2C_Protocol.S_M_ReadyForStart)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_M_ReadyForStart::ByteSizeLong(const MessageLite& base) {
          const S_M_ReadyForStart& this_ = static_cast<const S_M_ReadyForStart&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_M_ReadyForStart::ByteSizeLong() const {
          const S_M_ReadyForStart& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:S2C_Protocol.S_M_ReadyForStart)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 countdown = 1;
            if (this_._internal_countdown() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_countdown());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_M_ReadyForStart::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_M_ReadyForStart*>(&to_msg);
  auto& from = static_cast<const S_M_ReadyForStart&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_Protocol.S_M_ReadyForStart)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_countdown() != 0) {
    _this->_impl_.countdown_ = from._impl_.countdown_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_M_ReadyForStart::CopyFrom(const S_M_ReadyForStart& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_Protocol.S_M_ReadyForStart)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_M_ReadyForStart::InternalSwap(S_M_ReadyForStart* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.countdown_, other->_impl_.countdown_);
}

::google::protobuf::Metadata S_M_ReadyForStart::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace S2C_Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_S2C_5fProtocol_5fMole_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
