// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: S2C_Protocol_Enum.proto
// Protobuf C++ Version: 5.29.5

#include "S2C_Protocol_Enum.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace S2C_Protocol {
}  // namespace S2C_Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_S2C_5fProtocol_5fEnum_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_S2C_5fProtocol_5fEnum_2eproto = nullptr;
const ::uint32_t TableStruct_S2C_5fProtocol_5fEnum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_S2C_5fProtocol_5fEnum_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027S2C_Protocol_Enum.proto\022\014S2C_Protocol*"
    "\251\005\n\005MsgId\022\r\n\tS_WELCOME\020\000\022\r\n\tC_WELCOME\020\001\022"
    "\026\n\022S_WELCOME_RESPONSE\020\002\022\017\n\013S_ENCRYPTED\020\003"
    "\022\017\n\013C_ENCRYPTED\020\004\022\013\n\007C_LOGIN\020\005\022\013\n\007S_LOGI"
    "N\020\006\022\024\n\020C_CREATE_ACCOUNT\020\007\022\024\n\020S_CREATE_AC"
    "COUNT\020\010\022\014\n\010C_LOGOUT\020\t\022\014\n\010S_LOGOUT\020\n\022\027\n\023C"
    "_MATCHMAKE_REQUEST\020\013\022\027\n\023S_MATCHMAKE_REQU"
    "EST\020\014\022\026\n\022C_MATCHMAKE_CANCEL\020\r\022\026\n\022S_MATCH"
    "MAKE_CANCEL\020\016\022\032\n\026S_MATCHMAKE_KEEP_ALIVE\020"
    "\017\022\032\n\026C_MATCHMAKE_KEEP_ALIVE\020\020\022\024\n\020S_REDO_"
    "MATCHMAKE\020\021\022\031\n\025S_EXCLUDED_FROM_MATCH\020\022\022\031"
    "\n\025S_MATCHMAKE_COMPLETED\020\023\022!\n\035C_GAME_SCEN"
    "E_LOADING_PROGRESS\020\024\022\022\n\016S_GAME_STARTED\020\025"
    "\022\030\n\024C_REQUEST_GAME_STATE\020\026\022\024\n\020S_TESTGAME"
    "_STATE\020\027\022\024\n\020S_PINGPONG_STATE\020\030\022\023\n\017S_DANM"
    "AKU_STATE\020\031\022\034\n\030S_DELTA_GAME_OBJECT_SOFT\020"
    "\032\022\034\n\030S_DELTA_GAME_OBJECT_HARD\020\033\022\027\n\023S_SPA"
    "WN_GAME_OBJECT\020\034\022\031\n\025S_DESPAWN_GAME_OBJEC"
    "T\020\035B\033\252\002\030Google.Protobuf.Protocolb\006proto3"
};
static ::absl::once_flag descriptor_table_S2C_5fProtocol_5fEnum_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_S2C_5fProtocol_5fEnum_2eproto = {
    false,
    false,
    760,
    descriptor_table_protodef_S2C_5fProtocol_5fEnum_2eproto,
    "S2C_Protocol_Enum.proto",
    &descriptor_table_S2C_5fProtocol_5fEnum_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_S2C_5fProtocol_5fEnum_2eproto::offsets,
    file_level_enum_descriptors_S2C_5fProtocol_5fEnum_2eproto,
    file_level_service_descriptors_S2C_5fProtocol_5fEnum_2eproto,
};
namespace S2C_Protocol {
const ::google::protobuf::EnumDescriptor* MsgId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_S2C_5fProtocol_5fEnum_2eproto);
  return file_level_enum_descriptors_S2C_5fProtocol_5fEnum_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgId_internal_data_[] = {
    1966080u, 0u, };
bool MsgId_IsValid(int value) {
  return 0 <= value && value <= 29;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace S2C_Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_S2C_5fProtocol_5fEnum_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
